## Numpy
##### NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. 
##### - Tutorial Points

### Load in NumPy (remember to pip install numpy first)

In [2]:
import numpy as np

### The Basics

In [6]:
alist = [1,2,3]
print(type(alist))

<class 'list'>


In [28]:
a = np.array([1,2,3,5], dtype='int')
print(a)

[1 2 3 5]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.shape

(3,)

In [11]:
# Get Shape
b.shape

(2, 3)

In [21]:
# Get Type
a.dtype

dtype('int32')

In [26]:
# Get Size
a.itemsize

8

In [29]:
# Get total size
a.nbytes

16

In [31]:
# Get number of elements
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [32]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [33]:
# Get a specific element [r, c]
a[1, 5]

13

In [39]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# Get a specific column
a[:, 4]

array([ 5, 12])

In [43]:
a[0][::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [40]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [44]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [52]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [53]:
# Get specific element (work outside in)
b[0,1,1]

4

In [54]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [56]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [59]:
# All 0s matrix
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [62]:
# Any other number
np.full((2,2), 100)

array([[100, 100],
       [100, 100]])

In [63]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [68]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.19577975, 0.50301592],
       [0.77636923, 0.36301558],
       [0.54018772, 0.96956572],
       [0.25315135, 0.37198349]])

In [67]:
# Random Integer values
np.random.randint(-800,800, size=(3,3))

array([[-103,  365, -531],
       [-528, -361, -157],
       [ 415, -140, -517]])

In [69]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,5, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [72]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [76]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [77]:
b

array([100,   2,   3])

### Mathematics

In [78]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [79]:
a + 2

array([3, 4, 5, 6])

In [80]:
a - 2

array([-1,  0,  1,  2])

In [81]:
a * 2

array([2, 4, 6, 8])

In [82]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [83]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [84]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [85]:
a % 2

array([1, 0, 1, 0], dtype=int32)

In [86]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [88]:
np.sin(a)/np.cos(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [89]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [90]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [93]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [94]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [95]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.min(stats)

1

In [98]:
np.max(stats, axis=0)

array([4, 5, 6])

In [97]:
np.max(stats, axis=1)

array([3, 6])

In [99]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [120]:
a = np.full((2,2), 1)
a1 = np.array([[2,3],[4,9]])
b = np.random.random((5,1,4))

In [104]:
a.mean()

76.0

In [105]:
b

array([[[0.57575839, 0.92373488, 0.71461663, 0.85955608]],

       [[0.03565282, 0.44534711, 0.04710137, 0.76645449]],

       [[0.38900911, 0.93665798, 0.85665537, 0.94875404]],

       [[0.6833847 , 0.7672205 , 0.32811196, 0.2762067 ]],

       [[0.47943616, 0.43203769, 0.40135757, 0.55166981]]])

In [111]:
np.median(a)

76.0

In [121]:
np.corrcoef(a,a1)

c:\programdata\anaconda3\envs\virtualpython2\lib\site-packages\numpy\lib\function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan,  1.,  1.],
       [nan, nan,  1.,  1.]])

In [122]:
np.std(b)

0.25690455836538506

### Reorganizing Arrays

In [125]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before,before.shape)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[1 2 3 4 5 6 7 8]]


In [127]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v2,v2,v1,v2])

array([[5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [129]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [130]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

#### List Comprehensions

In [139]:
x = []
for i in range(5):
    if i!=3:
        x.append(i**2)

In [140]:
x

[0, 1, 4, 16]

In [142]:
y = [i**2 for i in range(5) if i!=3]

In [143]:
y

[0, 1, 4, 16]